In [1]:
import numpy as np

In [11]:
J_link = np.random.randint(10, size=(4, 6))



print(np.size(J_link))
print(J_link)
        
        
#         # after computing the jacobian for the elbow, we need to convert it to a full size jacobian 
# J = np.zeros((6, 7)) # Total Jacobain matrix. Fill in with J_link of elbow
        
# num_rows, num_cols = J_link.shape

# # print(n)
        
# J[0:6, 0:4] = J_link

# J[0:3,:] # take only linear part of the jacobian

J = np.pad(J_link, [(0, 1), (0, 1)], mode='constant')

print(np.size(J))
print(J)

24
[[3 5 4 3 0 3]
 [5 4 9 6 1 5]
 [8 7 8 9 9 6]
 [5 6 7 2 0 6]]


ValueError: could not broadcast input array from shape (4,6) into shape (6,4)